#name: CI
#on: [push, workflow_dispatch]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#    - run: echo "hello world"
#

name: CI
on: push
env:
  env_var: ${{ vars.REPO_VAR }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ env.env_var }}
